name: Bugs
description: Report issues or bug on the server.
labels: [ "status: needs triage", "type: bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Please be as detailed as possible so that we may consider and review the request easier.
        We ask that you search all the issues to avoid a duplicate feature request. If one exists, please reply if you have anything to add.

  - type: textarea
    attributes:
      label: What server does this bug related to?
      description: Discord Guild, Queue Server, Vanilla Server
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: What you expected to see.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Observed/Actual behavior
      description: What you actually saw.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps/models to reproduce
      description: This may include a build schematic, a video, or detailed instructions to help reconstruct the issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other
      description: Add any other context or screenshots about the bug below.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Before submitting this bug reportt, please search our issue tracker to ensure your bug has not
        already been addressed.
